version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: logoped-krd:web
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://logoped-krd.ru
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - TURNSTILE_SITEKEY=${TURNSTILE_SITEKEY}
      - TURNSTILE_SECRET=${TURNSTILE_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_FROM=${SMTP_FROM}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - REQUIRE_EMAIL_VERIFIED=${REQUIRE_EMAIL_VERIFIED}
    depends_on:
      - db
    ports:
      - "127.0.0.1:127.0.0.1:3000:3000"
    networks:
      - webnet

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-logoped}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ssl_certs:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"   # Web UI
    environment: {}
    networks:
      - webnet

volumes:
  pgdata:
  ssl_certs:

networks:
  webnet:
