name: E2E (Playwright)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: logoped
        options: >-
          --health-cmd="pg_isready -U app -d logoped" \
          --health-interval=5s --health-timeout=5s --health-retries=10

    env:
      NODE_ENV: test
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: e2e-e2e-secret
      ENABLE_TEST_LOGIN: '1'
      DATABASE_URL: postgresql://app:app@localhost:5432/logoped?schema=public
      CI: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run DB migrations
        run: npx prisma migrate deploy

      - name: Seed E2E data
        run: node prisma/seed-e2e.cjs

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
