version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: logoped-krd:web
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://logoped-krd.ru
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-logoped}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ssl_certs:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - webnet

volumes:
  pgdata:
  ssl_certs:

networks:
  webnet:
